sudo : required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - cd tests
  - echo $PATH
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.5.6/bin
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - python test_login_page.py
after_script:
  - cd ..
  - python app.py
#script:
#  – python tests/test_login_page.py